@startuml HOMEX

left to right direction

actor "Người dùng chung" as User
actor "Bệnh nhân" as Patient
actor "Bác sĩ" as Doctor
actor "Quản trị viên" as Admin

rectangle "Quản lý hệ thống đặt lịch khám bệnh HOMEX" {
    usecase "Quản lý thông tin cá nhân" as info_management
    usecase "Quản lý bác sĩ" as doctor_management
    usecase "Quản lý bệnh nhân" as patient_management
    usecase "Quản lý blog" as blog_management
    usecase "Quản lý lịch làm việc của bác sĩ" as workSchedule_management
    usecase "Quản lý cuộc hẹn" as appointment_management
    usecase "Đặt lịch hẹn" as appointment_book
    usecase "Duyệt lịch" as approve
    usecase "Quản lý giao dịch" as transaction_management
    usecase "Quản lý danh sách hướng dẫn" as instrument_management
    
}

Admin -- doctor_management
Admin -- patient_management
Admin -- workSchedule_management
Admin -- blog_management
Admin -- appointment_management
Admin -- transaction_management
Admin -- instrument_management

User -- info_management

Patient -- appointment_book
Patient -- appointment_management

Doctor -- approve
Doctor -- workSchedule_management
Doctor -- patient_management

User <|-- Patient
User <|-- Doctor
User <|-- Admin

@enduml
