
@startUML CTUTCare+_Class_Final
left to right direction
' --------------- ACTOR ---------------
' Not null: fullname, phoneNumber, password, isDel
' priceAppointment, licenseNumber

class User {
    + ID: string
    + fullname: string 
    + dateOfBirth: date
    + gender: string
    + email: string
    + phoneNumber: string
    + address: string
    + image: string
    + password: string
    + isDel: bool

    + UpdateProfile(): void
    + ChangePassword(): void
    ' + ForgotPassword(): void
}

class Admin {
    + ManageUsers(): void
    + ManageAppointments(): void
    + ManageDoctors(): void
    + ManageSpecialties(): void
    ' + ManageClinics(): void
}

class Doctor {
    + bio: string
    + consultantFee: double
    + qualification: string
    + specialtyYearExp: int

    + ManagementAppointments(): List<Appointment>
    + ManagementSchedule(): void
    + ViewPatients(): List<Patient>
    ' + CreateMedicalRecord(): void
}

class Patient {
    ' + medicalHistory: string
    ' + insuranceNumber: string
    + bloodType: string

    + BookAppointment(): void
    + CancelAppointment(): void
    ' + ViewMedicalRecords(): List<MedicalRecord>
}

class Appointment {
    + ID: string
    + patientName: string
    + patientPhoneNumber: string
    + patientEmail: string
    + patientGender: string
    + forWho: string
    + patientDob: date
    + status: string
    + price: double
    + appointmentDate: date
    + appointmentTime: string
    + note: string
    + result: string
    + reason: string
    + paymentStatus: string
    ' MedicalRecord

    + manageAppointment(): void
}

class MomoPayment {
    + ID: string
    + status: string
    + linkData: string
    + createdAt: date

    + Payment(): void
}

class ScheduleWork {
    + ID: string
    + date: date
    + timeSlots: list<string>
    + status: string
    ' + time: string
    ' + time_start: string
    ' + time_end: string
    ' + maxPatients: int

    + manageSchedule(): void
}

class Specialty {
    + ID: string
    + name: string
    + image: string
    ' + description: text
    ' Clinic
    ' + clinicNumber: string
    ' + clinicAddress: string
    ' + clinicPhoneNumber: string

    + ManageSpecialty(): void
}

class Message {
    + ID: string
    + senderID: string
    + receiverID: string
    + content: string
    + attachment: string
    + timestamp: date
    + status: string

    + SendMessage(): void
    + DeleteMessage(): void
}

class Blog {
    + ID: string
    + title: string
    + content: string
    + image: string
    + createdAt: date
    + status: string

    + ManageBlog(): void
}

class Clinic {
    + ID: string
    + name: string
    + description: string

    + ManageClinic(): void
}

class Review {
    + ID: string
    + rate: int    
    + content: string
    + createdAt: date

    + Delete(): void
}

' --------------- RELATIONSHIPS ---------------
Admin --|> User
Doctor --|> User
Patient --|> User

ScheduleWork "1" -- "n" Doctor: "has"
Appointment "n" -- "1" Doctor: "booked with"
Appointment "n" -- "1" Patient: "booked by"
Specialty "1" -left- "n" Doctor: "specializes in"
MomoPayment "n" -right- "1" Patient: "paid by"

Patient "1" -right- "n" Message: "received by"
Admin"1" -left- "n" Message : "received by"

Blog "1" -- "n" Admin: "created by"
Specialty "1" -right- "n" Clinic: "has"
Clinic "1" -- "n" Admin: "managed by"

Review "n" -right- "1" Doctor:" "has"

Review "n" -- "1" Patient: "reviewed by"


@endUML



